apiVersion: v1
kind: Service
metadata:
  name: vets-service
  labels:
    {{- include "pet-clinic-vets-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pet-clinic-vets-service.selectorLabels" . | nindent 4 }}
