apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    {{- include "pet-clinic-discovery-server.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pet-clinic-discovery-server.selectorLabels" . | nindent 4 }}
