resources:
  - name: UIServiceDockerImage
    type: Image
    configuration:
      registry: jfrog_cloud
      sourceRepository: docker
      imageName: tomjfrog.jfrog.io/petclinic-microservices-virtual/pet_clinic_ui_service_docker_image
      imageTag: '${run_number}'
      autoPull: true
  - name: UIServiceBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrog_cloud
      buildName: petclinic_microservices_helm
      buildNumber: 1
  - name: PetClinicUIServiceHelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: jfrog_cloud
      repository: helm-local
      chart: pet-clinic-ui-service
      version: '0.1.${run_number}'
  - name: PetClinicUIServiceHelmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrog_cloud
      buildName: petclinic_microservices_helm
      buildNumber: 1
  - name: PetClinicUIServicePromotedHelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: jfrog_cloud
      repository: helm-prod-local
      chart: pet-clinic-ui-service
      version: '0.${run_number}.0'
  - name: UIServiceDockerImagePromotedBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrog_cloud
      buildName: petclinic_microservices_helm
      buildNumber: 1
pipelines:
  - name: pet_clinic_ui_service
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
           ArtIP: $(echo ${int_jfrog_cloud_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
    steps:
      - name: bld_ui_service
        type: MvnBuild
        configuration:
          sourceLocation: app/spring-petclinic-api-gateway
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: PetClinicProjectGitRepo
              trigger: false
          integrations:
            - name: jfrog_cloud
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
            - add_pipeline_variables JFROG_CLI_BUILD_NAME="UIServiceMavenBuild"
            - sed -ie 's/Default-Server/jfrog_cloud/g' $res_PetClinicProjectGitRepo_resourcePath/app/spring-petclinic-api-gateway/mvn-art-config
          onComplete:
            - echo $run_var
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
          onSuccess:
            - rm -r ${steplet_run_state_dir}/jfrog
      - name: bld_ui_service_docker_image
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: app/spring-petclinic-api-gateway
          dockerFileName: Dockerfile
          dockerImageName: tomjfrog.jfrog.io/petclinic-microservices-virtual/pet_clinic_ui_service_docker_image
          dockerImageTag: '${run_number}'
          integrations:
            - name: jfrog_cloud
          inputResources:
            - name: PetClinicProjectGitRepo
              trigger: false
          outputResources:
            - name: UIServiceDockerImage
          inputSteps:
            - name: bld_ui_service
        execution:
          onStart:
            - sed -i "s#docker.artifactory#tomjfrog.jfrog.io/petclinic-microservices-virtual/#" $res_PetClinicProjectGitRepo_resourcePath/app/spring-petclinic-api-gateway/Dockerfile
            - sed -i "s/artifactory-unified.soleng-us.jfrog.team/${ArtIP}/" $res_PetClinicProjectGitRepo_resourcePath/app/spring-petclinic-api-gateway/Dockerfile
          onComplete:
            - echo $step_env_var2
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
      - name: push_ui_service_docker_image
        type: DockerPush
        configuration:
          affinityGroup: bldGroup
          targetRepository: petclinic-microservices-virtual
          forceXrayScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: jfrog_cloud
          inputSteps:
            - name: bld_ui_service_docker_image
          outputResources:
            - name: UIServiceBuildInfo
  - name: pet_clinic_ui_service_helm_deploy
    steps:
      - name: helm_build
        type: HelmPublish
        configuration:
          chartPath: app/spring-petclinic-api-gateway/pet-clinic-ui-service
          autoPublishBuildInfo: true
          helmVersion: 3
          flags: "-u"
          inputResources:
            - name: PetClinicProjectGitRepo
              trigger: false
            - name: UIServiceBuildInfo
              trigger: true
            - name: PetClinicDiscoveryServerPromotedHelmBuildInfo
              trigger: false
          outputResources:
            - name: PetClinicUIServiceHelmChart
            - name: PetClinicUIServiceHelmBuildInfo
        execution:
          onStart:
            - helm init --client-only --skip-refresh
            - helm repo rm stable
            - helm repo add stable https://charts.helm.sh/stable
            - pushd $res_PetClinicProjectGitRepo_resourcePath/app/spring-petclinic-api-gateway/pet-clinic-ui-service
            - add_pipeline_variables triggerBuildInfoNumber="${res_UIServiceBuildInfo_buildNumber}"
            - sed -i "s/0.1.0/0.$run_number.0/g" Chart.yaml
            - sed -i "s/1.1/$triggerBuildInfoNumber/" values.yaml
            - sed -i "s/0.19.0/0.${res_PetClinicDiscoveryServerPromotedHelmBuildInfo_buildNumber}.0/" requirements.yaml
      - name: deploy_helm
        type: HelmDeploy
        configuration:
          releaseName: ui-service
          helmVersion: 3
          integrations:
            - name: tomj_gke_cluster #SolEngUS
            - name: gcp_service_account_for_gke_cluster # GCP Service Account JSON Key
          inputResources:
            - name: PetClinicUIServiceHelmChart
          flags: '--namespace default --force'
          valueFilePaths:
            - values.yaml
        execution:
          onStart:
            - helm init --client-only --skip-refresh
            - helm repo rm stable
            - helm repo add stable https://charts.helm.sh/stable
            - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            - apt-get update && apt-get install google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin
            - apt-get update && apt-get --only-upgrade install google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-config-connector google-cloud-sdk-harbourbridge google-cloud-sdk-app-engine-java google-cloud-sdk google-cloud-sdk-spanner-emulator google-cloud-sdk-package-go-module google-cloud-sdk-skaffold kubectl google-cloud-sdk-terraform-tools google-cloud-sdk-kubectl-oidc google-cloud-sdk-cbt google-cloud-sdk-log-streaming google-cloud-sdk-local-extract google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-grpc google-cloud-sdk-app-engine-python google-cloud-sdk-app-engine-go google-cloud-sdk-anthos-auth google-cloud-sdk-nomos google-cloud-sdk-cloud-run-proxy google-cloud-sdk-firestore-emulator google-cloud-sdk-gke-gcloud-auth-plugin google-cloud-sdk-cloud-build-local google-cloud-sdk-minikube google-cloud-sdk-kpt google-cloud-sdk-bigtable-emulator google-cloud-sdk-datastore-emulator
            - printenv int_gcp_service_account_for_gke_cluster_GCLOUD_SERVICE_ACCOUNT_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            - gcloud container clusters get-credentials tomj-cluster-003 --zone us-east1-c --project soleng-dev
          onSuccess:
            - kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=config-server -n default --timeout=600s
            - kubectl get pods --namespace default
          onComplete: #always
            - add_run_variables pod_name="$(kubectl get pods --no-headers=true | awk '/ui-service/{print $1}')"
            #- add_run_variables pod_ip="$(kubectl describe pod $pod_name | grep "IP:" | awk '{print $2}')"
            - add_run_variables pod_ip="$(kubectl describe service ui-service | grep "LoadBalancer Ingress" | awk '{print $3}')"
            - echo "pod name is $pod_name and pod ip is $pod_ip"
      - name: test_docker_app
        type: Bash
        configuration:
          inputSteps:
            - name: deploy_helm
          integrations:
            - name: jfrog_cloud
        execution:
          onStart:
            - echo "testing docker application" #$latest_docker_ver
          onExecute:
            - echo "testing"
            #- PAGE=$(curl -s "http://localhost:8088/index.html" | tr '[:upper:]' '[:lower:]')
            #- if [[ $PAGE =~ "swampup" ]]; then echo "swampup found" fi
            - if curl -Is "http://$pod_ip:8080"; then add_run_variables dockerAppStatus="pass"; else add_run_variables dockerAppStatus="fail"; fi
            #- if curl -Is "http://$pod_ip:8080/index.html"; then add_run_variables docker_promotion_repo=petclinic-microservices-docker-prod-local; else add_run_variables docker_promotion_repo=docker-archive-local; fi
          onComplete: #always
            - echo "testing done"
            - curl -u ${int_jfrog_cloud_user}:${int_jfrog_cloud_apikey} --header "Content-Type:application/json" --request PATCH  ${int_jfrog_cloud_url}/api/metadata/docker-dev-local/pet_clinic_ui_service_docker_image/$triggerBuildInfoNumber --data '{"props":{"unittest":"passed"}}'
      - name: scan_ui_service_docker_image
        type: XrayScan
        configuration:
          failOnScan: false
          inputSteps:
            - name: test_docker_app
          inputResources:
            - name: UIServiceBuildInfo
              trigger: false
        execution:
          onStart:
            - echo "Xray scan to start"
          onComplete: #always
            - echo "Xray scan complete"
      - name: promote_docker_app
        type: PromoteBuild
        configuration:
          targetRepository: petclinic-microservices-docker-prod-local
          integrations:
            - name: jfrog_cloud
          inputSteps:
            - name: scan_ui_service_docker_image
          inputResources:
            - name: UIServiceBuildInfo
              trigger: false
          outputResources:
            - name: UIServiceDockerImagePromotedBuildInfo
        execution:
          onStart:
            - echo "Promotion repo is petclinic-microservices-docker-prod-local"
          onComplete: #always
            - echo "Promotion complete"
            - curl -u ${int_jfrog_cloud_user}:${int_jfrog_cloud_apikey} --header "Content-Type:application/json" --request PATCH  ${int_jfrog_cloud_url}/api/metadata/petclinic-microservices-docker-prod-local/pet_clinic_ui_service_docker_image/$triggerBuildInfoNumber --data '{"props":{"xrayscan":"passed"}}'
      - name: promote_helm_chart
        type: PromoteBuild
        configuration:
          targetRepository: helm-prod-local
          integrations:
            - name: jfrog_cloud
          inputSteps:
            - name: promote_docker_app
          inputResources:
            - name: PetClinicUIServiceHelmBuildInfo
          outputResources:
            - name: PetClinicUIServicePromotedHelmBuildInfo